# docker-compose.test.yml
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=expense_tracker_test
    ports:
      - '5433:5432'
    tmpfs:
      - /var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d expense_tracker_test"]
      interval: 5s
      timeout: 5s
      retries: 5

# Eliminar la sección de volumes
